openapi: 3.0.0
info:
  title: Photo Rating App API
  version: 1.0.0

paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                gender:
                  type: string
                  enum: [male, female, other]
                age:
                  type: integer
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
        '500':
          description: Server error

  /api/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid credentials
        '500':
          description: Server error

  /api/reset-password-request:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset link sent
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Server error

  /api/upload-photo:
    post:
      summary: Upload a new photo
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoUrl:
                  type: string
      responses:
        '201':
          description: Photo uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  photoId:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/photos-for-rating:
    get:
      summary: Get photos for rating
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: gender
          schema:
            type: string
        - in: query
          name: minAge
          schema:
            type: integer
        - in: query
          name: maxAge
          schema:
            type: integer
      responses:
        '200':
          description: List of photos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    url:
                      type: string
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/rate-photo:
    post:
      summary: Rate a photo
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                rating:
                  type: number
      responses:
        '200':
          description: Photo rated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  newAverageRating:
                    type: number
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Photo not found
        '500':
          description: Server error

  /api/user-points:
    get:
      summary: Get user points
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User points
          content:
            application/json:
              schema:
                type: object
                properties:
                  points:
                    type: integer
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
